[package]
name = "sophia"
version = "0.1.0"
edition = "2021"
authors = ["Wayne Wu <wayne-wu@outlook.com> (https://wayne-wu.com)"]
description = "A simple server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "entity", "migration"]

[dependencies]
anyhow = { version = "1.0.77", features = ["backtrace"] }
axum = { version = "0.7.2", features = [ "default", "http2", "macros" ] }
clap = { version = "4.4.11", features = ["default", "derive"] }
config = "0.13.4"
dotenv = "0.15.0"
entity = { path = "entity"}
jsonwebtoken = "9.2.0"
migration = { path = "migration"}
once_cell = "1.19.0"
sea-orm = { version = "0.12", features = [ "runtime-tokio-rustls", "sqlx-postgres", "sqlx-mysql", "sqlx-sqlite", "macros", "with-chrono", "with-json" ]}
serde = "1.0.193"
serde-enum-str = "0.4.0"
serde_json = "1.0.108"
serde_repr = "0.1.17"
thiserror = "1.0.52"
tokio = { version = "1.35.1", features = ["full"] }
enum-meta = { git = "https://github.com/WayneWu98/enum-meta.git" }
tracing = { version = "0.1.40", features = ["default", "async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tower-http = { version = "0.5.0", features = ["trace"] }
tracing-appender = "0.2.3"
